#!/bin/bash

# SPDX-FileCopyrightText: 2026 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
# Software-Engineering: 2026 Intevation GmbH <https://intevation.de>
#
# SPDX-License-Identifier: Apache-2.0

# Converts a blocklist managed by the operator into Apache configuration fragments.
# Edit the files in contrib/blocklists/, run this script and then reload Apache.
#
# Environment variables:
#   OUTPUT_DIR   Directory to write generated conf fragments (default: /etc/apache2/conf-available/)
#   NO_RELOAD    Set to 1 to skip the Apache reload (default: 0)
#
# Two files are generated:
#   blocklist-cidr.conf   — <RequireAll> block, include inside the <Location /> block in your Apache site configuration
#   blocklist-env.conf    — SetEnvIf lines, use for Rewrite config at vhost level before the RewriteRule in your Apache site configuration
# See contrib/apache-site.conf for an example.

set -euo pipefail

SCRIPT_DIR="$(dirname "$0")"
BLOCKLIST_DIR="${SCRIPT_DIR}/blocklists"
OUTPUT_DIR="${OUTPUT_DIR:-/etc/apache2/conf-available/}"
NO_RELOAD="${NO_RELOAD:-0}"

CIDR_FILE="${BLOCKLIST_DIR}/cidr.txt"
UA_FILE="${BLOCKLIST_DIR}/useragents.txt"
COUNTRY_FILE="${BLOCKLIST_DIR}/countries.txt"
CIDR_OUT="${OUTPUT_DIR}/blocklist-cidr.conf"
ENV_OUT="${OUTPUT_DIR}/blocklist-env.conf"

# CIDR blocklist
echo '# Auto-generated by update-blocklists.sh — do not edit manually' > "$CIDR_OUT"
echo '<RequireAll>' >> "$CIDR_OUT"
echo '    Require all granted' >> "$CIDR_OUT"
cidr_count=0
while IFS= read -r line; do
    # Ignore comments (lines starting with #)
    entry="${line%%#*}"
    [ -z "$entry" ] && continue
    echo "    Require not ip $entry" >> "$CIDR_OUT"
    cidr_count=$((cidr_count + 1))
done < "$CIDR_FILE"
echo '</RequireAll>' >> "$CIDR_OUT"

# User Agent and country blocklists
echo '# Auto-generated by update-blocklists.sh — do not edit manually' > "$ENV_OUT"

ua_count=0
while IFS= read -r line; do
    entry="${line%%#*}"
    [ -z "$entry" ] && continue
    echo "SetEnvIf User-Agent \"$entry\" blocked_ua" >> "$ENV_OUT"
    ua_count=$((ua_count + 1))
done < "$UA_FILE"

country_count=0
while IFS= read -r line; do
    entry="${line%%#*}"
    [ -z "$entry" ] && continue
    echo "SetEnvIf GEOIP_COUNTRY_CODE \"^$entry\$\" blocked_country" >> "$ENV_OUT"
    country_count=$((country_count + 1))
done < "$COUNTRY_FILE"

echo "Blocklists written: $cidr_count CIDRs, $ua_count User-Agents, $country_count countries"

# Reload Apache
if [ "$NO_RELOAD" -eq 0 ]; then
    if command -v apachectl > /dev/null 2>&1; then
        apachectl graceful
        echo 'Apache reloaded.'
    else
        echo 'apachectl not found - reload Apache manually/with systemd to apply changes.'
    fi
else
    echo 'Skipping Apache reload (NO_RELOAD=1).'
fi
